### PR TITLE
Adds SPICEApplications.jl as subpackage

### PR DESCRIPTION
**Pull request by jdc-pub**
I have previously released [`SPICEApplications.jl`](https://github.com/cadojo/SPICEApplications.jl), which provides hooks into SPICE Toolkit executables (applications) provided by `CSPICE_jll`. I think it might fit in nicely with this package, and if you agree, I would be interested in helping to maintain it. 

What do you think?

### CODE REVIEW

**Comment by helgee** [comment]
Sounds good 👍 I will look into this in more detail over the weekend.

**Comment by helgee** [comment]
Sorry for the delay @cadojo. As you can see, help with the maintenance of this package is desperately needed 🙈

**Comment by jdc-pub** [comment]
No worries, thank you! I will need to do a bit more work here to fully port SPICEApplications into the SPICE repo. I'll add another PR which merges the documentation branches too, and updates CI, etc. If you're comfortable making me maintainer, I can add CI workflow dispatch for my own debugging in getting that up and running. Either way works for me :)

**Comment by jdc-pub** [comment]
@helgee I understand you are on a hiatus from @JuliaAstro work. Is there another primary maintainer of this repository who I should contact? I would like to be added as a maintainer so I can setup and debug CI for `SPICEApplications`.

**Comment by helgee** [comment]
Granted you maintainer rights @cadojo

**Pull request merged**
